var product=[{
    "id": 0,
    "title":"",
    "price":"",
    "brand":"",
    "ram":"",
    "discription":"",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png",
    "Display":"",
    "Processor":"",
    "Memory":"",
    "System":"",
    "Battery":"",
    "Operating":"",
},{
    "id": 1,
    "title":"Samsung Galaxy S24 Ultra",
    "price":"35000",
    "brand":" Samsung galaxy",
    "ram":"Face ID, accelerometer, gyro, proximity, compass, barometer",
    "discription":"Actual storage availability may vary depending on pre-installed software.",
    "image":"samsung-galaxy-s24-ultra-5g-sm-s928-stylus.png",
    "Display":" 6.8-inch Dynamic AMOLED with a 120Hz refresh rate, providing vibrant and smooth visuals.",
    "Processor":" Powered by the Qualcomm Snapdragon 8 Gen 3 chipset, ensuring top-tier performance.",
    "Memory":"Equipped with 12GB of RAM and available in storage options of 256GB, 512GB, and 1TB, catering to various user needs.",
    "System":"Features a 200MP wide camera, delivering exceptional photo and video quality.",
    "Battery":"Houses a 5,000 mAh battery, supporting 45W wired charging and 15W wireless charging, offering substantial battery life and quick recharge times.",
    "Operating":" Runs on Android 14, with support for up to seven major upgrades, ensuring longevity in software updates.",
},{
    "id": 2,
    "title":"Iphone-14-pro",
    "price":"152,000",
    "brand":"Iphone",
    "ram":"Face ID, accelerometer, gyro, proximity, compass, barometer",
    "discription":"Available. Released 2022, September 16",
    "image":"apple-iphone-14-pro.png",
    "Display":"LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM)",
    "Processor":"with stereo speakers",
    "Memory":"128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM, 1TB 6GB RAM",
    "System":"	48 MP, f/1.8, 24mm (wide), 1/1.28 1.22µm, dual pixel PDAF, sensor-shift OIS12 MP f/2.8, 77mm (telephoto), 1/3.5 1.0µm, PDAF, OIS, 3x optical zoom12 MP f/2.2 13mm 120˚ (ultrawide) 1/2.55 1.4µm dual pixel PDAF",
    "Battery":"Li-Ion 3200 mAh (12.38 Wh)",
    "Operating":"",
},{
    "id": 3,
    "title":"tecno-spark-20-pro",
    "price":"28999",
    "brand":"Tecno",
    "discription":"Available. Released 2023, December",
    "ram":"Fingerprint (side-mounted), accelerometer, proximity, compass",
    "image":"tecno-spark-20-pro.png",
    "Display":" Size:6.78 inches, 109.2 cm2 (~84.5% screen-to-body ratio)",
    "Processor":"Yes, with stereo speakers",
    "Memory":"microSDXC 256GB 8GB RAM",
    "System":"108 MP, f/1.8, (wide), 1/1.67, 0.64µm, PDAF2 MP, (macro)",
    "Battery":"5000 mAh",
    "Operating":"",
},{
    "id": 4,
    "title":"Nokia-G21",
    "price":"24699",
    "brand":"Iphone",
    "discription":"Available. Released 2022, February 15",
    "ram":"Fingerprint (side-mounted), accelerometer, proximity",
    "image":"nokia-g21-dusk.png",
    "Display":" size:6.5 inches, 102.0 cm2 (~81.6% screen-to-body ratio)",
    "Processor":"Yes, with stereo speakers",
    "Memory":"64GB 3GB RAM, 64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM",
    "System":"50 MP, f/1.8, 28mm (wide), 1/2.76, 0.64µm, PDAF",
    "Battery":"Li-Po 5050 mAh",
    "Operating":"",
}
]